services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb # this is the DNS name => so you need to connect to "mongodb://mongodb:27017" from within your application
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - show-case-network

  # Access this Web UI at http://localhost:8081
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - show-case-network

volumes:
  data-volume:

networks:
  show-case-network:
    driver: bridge