services:
  mongo:
    image: mongo
    container_name: mongodb # this is the DNS name => so you need to connect to "mongodb://mongodb:27017" from within your application
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always
    networks:
      - show-case-network

  # Access this Web UI at http://localhost:8081
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    restart: always
    networks:
      - show-case-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    container_name: keycloak-test
    command:
      - start-dev
      - --import-realm
      - --spi-import-strategy=OVERWRITE_EXISTING
      - --features=admin-fine-grained-authz
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - 8082:8080
    restart: always
    volumes:
      - ../docker-compose/keycloak/themes/cheshire:/opt/keycloak/themes/cheshire
      - ../docker-compose/keycloak/realm.json:/opt/keycloak/data/import/realm.json

volumes:
  data-volume:

networks:
  show-case-network:
    driver: bridge