

spring:
  application:
    name: showcase
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/show-case?authSource=admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/showcase
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    enabled: true
    oauth:
      client-id: local-client
      client-secret: AE0vOfVykNWR91eMjAPvKpgW9wlbOSG4
server:
  port: 8080

logging:
  level:
    com.whoisacat: trace
    sun: warn
    root: warn