

spring:
  application:
    name: showcase

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/showcase
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5439/cf-expenses-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    platform: postgresql
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    enabled: true
    oauth:
      client-id: local-client
      client-secret: AE0vOfVykNWR91eMjAPvKpgW9wlbOSG4
server:
  port: 8080

logging:
  level:
    sun: error
    root: debug